#ifndef MSGS_H
#define MSGS_H

// alphabetical ordered:
#define ACCPERR "Sock: Accept error \0"
#define BINDERR "Sock: Bind error \0"
#define CFILEOK "Parsing config file \0"
#define CFILENO "Failed opening config file \0"
#define CONTACT "Contact: http://www.yChat.org, Mail@yChat.org, ICQ: 11655527\0"
#define CLRHTML "HTML: Cleared the template cache \0"
#define DESCRIP "yChat++: Copyright (C) 2003 Paul C. Buetow, Volker Richter\0"
#define DOWNMSG "Shutting down \0"
#define GARBAGE "Initializing garbage collector \0"
#define GARBACT "Garbage collector activated \0"
#define GARNONE "Garbage: No garbage to remove available \0"
#define GARROOM "Garbage: Added room \0"
#define GARUSER "Garbage: Added user \0"
#define GARUSE2 "Garbage: Recycle user \0"
#define LISTERR "Sock: Listen error \0"
#define LOGERR1 "Logging: Could not open logfile \0"
#define LOGERR2 "Logging: No filename specified \0"
#define MODULEC "Caching \0"
#define MODULER "Requesting \0"
#define MODUNLO "Modl: Unloading all modules \0"
#define MODRELO "Modl: Reloading all modules \0"
#define MYMANAG "MySQL: \0" 
#define MYSCONN "MySQL: Creating connection \0"
#define MYSINIT "Initializing MySQL manager \0"
#define MYLIMIT "MySQL: Reached hardlimit of connections: \0"
#define MYINITC "MySQL: Initial connections: \0" 
#define MYINITM "MySQL: Max. connections: \0" 
#define MYERRO1 "MySQL error: Init failed \0"
#define MYERRO2 "MySQL error: Reached connection limit \0"
#define MYERRO3 "MySQL error: \0"
#define MYERRO4 "MySQL error: mysql_query failed\0"
#define MYERRO5 "MySQL error: Failed because of incomplete request\0"
#define MYWARN1 "MySQL warning: MySQL seems 0\0"
#define NEWREQU "Sock: New request \0"
#define NEWROOM "Chat: New room \0"
#define NEWUSER "Chat: New user \0"
#define NOFOUND "HTML: File not found \0"
#define POOLERR "Pool: Malloc error \0"
#define READERR "Sock: Read error \0"
#define REMROOM "Garbage: Removing room \0"
#define REMUSER "Garbage: Removing user \0"
#define REQUEST "Reqp: Request string \0"
#define SELCERR "Sock: Select error \0"
#define SEPERAT "-----------------------\0"
#define SESSION "Session: Count \0"
#define SESSDMP "Session: Dump of session\0"
#define REUROOM "Garbage: Reusing room object \0"
#define SOCKCRT "Sock: Created socket on \0"
#define SOCKERR "Sock: Can't create socket, trying next port \0"
#define SOCKRDY "Sock: Server socket is ready \0"
#define STARTMS "Initializing server socket \0"
#define TECACHE "HTML: Caching template \0"
#define TIMERAC "Initializing system timer\0"
#define TIMERUP "Timer: System uptime \0"
#define VERSION "yChat++ Advanced 0.6-CURRENT (CVS)\0"
#define BUILDNR 32
#define UNAME "unknown\0" 

#endif
